name: Fast checks

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - run: pip install flake8
    - name: Flake8 lint Python code
      run: flake8

  mypy:
    name: Type checking
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - run: pip install mypy
    - name: Mypy type checking
      run: mypy src

  bandit:
    name: Security checking
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - run: pip install bandit
    - name: Bandit security checking
      run: bandit -r src -ll

  misspell:
    name: Check misspellings
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - name: Check misspellings
      uses: codespell-project/actions-codespell@v1
      with:
        builtin: clear,rare
        check_filenames: true
